#!/bin/sh --
# sx - start an xserver
# requires xauth Xorg /dev/urandom

cleanup() {
    if [ "$pid" ] && kill -0 "$pid" 2> /dev/null; then
        kill "$pid"
        wait "$pid"
        xorg=$?
    fi

    xauth remove "$1"

    if [ "$2" = exit ]; then
        exit "${xorg:-0}"
    fi
}

cfgdir=${XDG_CONFIG_HOME:-$HOME/.config}/sx
datadir=${XDG_DATA_HOME:-$HOME/.local/share}/sx
mkdir -p -- "$cfgdir" "$datadir"

export XAUTHORITY="${XAUTHORITY:-$datadir/xauthority}"
touch -- "$XAUTHORITY"

xauth add "$1" MIT-MAGIC-COOKIE-1 "$(od -An -N16 -tx /dev/urandom | tr -d ' ')"

trap 'cleanup "$1"; trap - INT; kill -INT "$$"' INT
trap 'cleanup "$1" exit' EXIT HUP TERM QUIT

# Xorg will check whether it inherited a USR1 with a disposition of SIG_IGN and
# use this state to reply back to the parent process with its own USR1.
# This is done to indicate that the server is ready to accept connections.
# Taking advantage of this feature allows launching the client directly from a
# USR1 signal trap which obviates the need to poll for server readiness.
trap 'DISPLAY="$1" exec "$cfgdir/sxrc" & wait "$!"' USR1

(trap '' USR1 && exec Xvfb "$@" -noreset -auth "$XAUTHORITY") & pid=$!
wait "$pid"
